

import javax.swing.*;
import java.io.*;
import java.util.Scanner;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */





class USERDATA
{



    public String Name;
    public String Phone;
    public String Email;
    public String Address;



    public USERDATA(String a, String b, String c ,String d) {
        this.Name=a;
        this.Phone=b;
        this.Email= c;
        this.Address= d;

    }



}









class AddressBook extends  JFrame {

    /**
     * Creates new form AddressBook
     */
    public AddressBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSpinner1 = new  JSpinner();
        jLabel1 = new  JLabel();
        jLabel2 = new  JLabel();
        jLabel3 = new  JLabel();
        jLabel4 = new  JLabel();
        nameTf = new  JTextField();
        phoneTf = new  JTextField();
        mailTf = new  JTextField();
        addressTf = new  JTextField();
        saveButton = new  JButton();
        editButton = new  JButton();
        showButton = new  JButton();
        search_byNameButton = new  JButton();
        Ta = new  JScrollPane();
        jTextArea1 = new  JTextArea();
        searchTf = new  JTextField();
        search_byPhoneButton = new  JButton();
        jLabel5 = new  JLabel();
        jLabel6 = new  JLabel();
        jLabel7 = new  JLabel();
        jLabel8 = new  JLabel();
        editSaveButton = new  JButton();

        setDefaultCloseOperation( WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Phone no.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("E-Mail :");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Address :");

        nameTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        phoneTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mailTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addressTf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        saveButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    saveButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        editButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        editButton.setText("EDIT");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        showButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        showButton.setText("SHOW");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    showButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        search_byNameButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        search_byNameButton.setText("SEARCH by name :");
        search_byNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_byNameButtonActionPerformed(evt);
            }
        });

        Ta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        Ta.setViewportView(jTextArea1);

        search_byPhoneButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        search_byPhoneButton.setText("SEARCH by phone :");
        search_byPhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_byPhoneButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("To Edit Your Saved Information :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("1. Enter Your Phone no.");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("2. Press Edit ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("3.Edit and Press \"SAVE NEW INFORMATION\"");

        editSaveButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        editSaveButton.setText("SAVE NEW INFORMATION");
        editSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveButtonActionPerformed(evt);
            }
        });

         GroupLayout layout = new  GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                                        .addComponent(searchTf)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel1,  GroupLayout.PREFERRED_SIZE, 122,  GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(nameTf,  GroupLayout.PREFERRED_SIZE, 312,  GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2,  GroupLayout.PREFERRED_SIZE, 122,  GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel4,  GroupLayout.PREFERRED_SIZE, 122,  GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel3,  GroupLayout.Alignment.TRAILING,  GroupLayout.PREFERRED_SIZE, 122,  GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(mailTf,  GroupLayout.PREFERRED_SIZE, 312,  GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(phoneTf,  GroupLayout.PREFERRED_SIZE, 312,  GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(addressTf,  GroupLayout.PREFERRED_SIZE, 312,  GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(244, 244, 244)
                                                                                .addComponent(showButton,  GroupLayout.PREFERRED_SIZE, 102,  GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 43, Short.MAX_VALUE)))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.TRAILING)
                                                        .addComponent(saveButton,  GroupLayout.PREFERRED_SIZE, 102,  GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(search_byNameButton,  GroupLayout.PREFERRED_SIZE, 220,  GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(search_byPhoneButton)
                                                .addGap(29, 29, 29))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Ta,  GroupLayout.PREFERRED_SIZE, 474,  GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel5,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel6,  GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                                                        .addComponent(jLabel7,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(editButton,  GroupLayout.PREFERRED_SIZE, 289,  GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(editSaveButton,  GroupLayout.PREFERRED_SIZE, 289,  GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1,  GroupLayout.PREFERRED_SIZE, 38,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameTf,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneTf,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2,  GroupLayout.PREFERRED_SIZE, 38,  GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(mailTf,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3,  GroupLayout.PREFERRED_SIZE, 38,  GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(addressTf,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4,  GroupLayout.PREFERRED_SIZE, 38,  GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton,  GroupLayout.PREFERRED_SIZE, 41,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showButton,  GroupLayout.PREFERRED_SIZE, 41,  GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                        .addComponent(search_byPhoneButton,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE)
                                        .addComponent(search_byNameButton,  GroupLayout.PREFERRED_SIZE, 41,  GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(searchTf,  GroupLayout.PREFERRED_SIZE, 46,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ta,  GroupLayout.PREFERRED_SIZE, 185,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5,  GroupLayout.PREFERRED_SIZE, 43,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton,  GroupLayout.PREFERRED_SIZE, 40,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editSaveButton,  GroupLayout.PREFERRED_SIZE, 40,  GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {



        Writer Out;
        Out = new BufferedWriter(new FileWriter("output.txt",true));


        String str = nameTf.getText() + "###"+  phoneTf.getText() + "###" + mailTf.getText() +  "###" + addressTf.getText() + "\n";
        Out.append(str);
        Out.close();







    }

    USERDATA[] Address = new USERDATA[5];




    public void storedata(){



        String Name;
        String phone;
        String email;
        String address;





        try {
            File Object = new File("C:\\Users\\shahr\\IdeaProjects\\Dina\\output.txt");
            Scanner Reader = new Scanner(Object);


            // employe = new Employe[5];
            // student = new Student[5];



            for (int i = 0; Reader.hasNextLine(); i++) {
                if (5 <= i) {
                    break;
                }
                String data = Reader.nextLine();


                String[] in = data.split("###");

                Name = in[0];
                phone = in[1];
                email = in[2];
                address = in[3];



                Address[i]= new USERDATA(Name,phone,email,address);


            }
            Reader.close();

        } catch (FileNotFoundException | NumberFormatException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }








    }







    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException {


        storedata();
        for (int i = 0; i < Address.length; i++) {


           if(searchTf.getText().equals(Address[i].Phone)) {

               jTextArea1.setText(Address[i].Phone);


           }
        /*    if(<Address[i].Phone){
                maxSalary=employe[i].salary;
                newid=employe[i].ID;
                newname=employe[i].name;

            }*/




        }








    }

    private void search_byNameButtonActionPerformed(java.awt.event.ActionEvent evt) {

        storedata();
        for (int i = 0; i < Address.length; i++) {


            if(searchTf.getText().equals(Address[i].Name)) {

                jTextArea1.setText(Address[i].Name);


            }
        /*    if(<Address[i].Phone){
                maxSalary=employe[i].salary;
                newid=employe[i].ID;
                newname=employe[i].name;

            }*/




        }



    }


    int serchid;

    private void search_byPhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {


        storedata();
        for (int i = 0; i < Address.length; i++) {


            if(searchTf.getText().equals(Address[i].Phone)) {

                jTextArea1.setText(Address[i].Phone);

                serchid=i;

            break;
            }
        /*    if(<Address[i].Phone){
                maxSalary=employe[i].salary;
                newid=employe[i].ID;
                newname=employe[i].name;

            }*/




        }


    }

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {



    }

    private void editSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {

        System.out.println("btn click");


         Address[serchid].Phone="01796911132";

        jTextArea1.setText("nbr change " +  Address[serchid].Phone);






         StringBuffer stringBufferOfData = new StringBuffer();


        String lineToEdit =Address[serchid].Phone;


        String replacementText = "01796911132";//read the line to replace

        //System.out.println(sb);//used for debugging to check that my stringbuffer has correct contents and spacing

        int startIndex = stringBufferOfData.indexOf(lineToEdit);//now we get the starting point of the text we want to edit
        int endIndex = startIndex + lineToEdit.length();//now we add the staring index of the text with text length to get the end index

        stringBufferOfData.replace(startIndex, endIndex, replacementText);//this is where the actual replacement of the text happens





    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for ( UIManager.LookAndFeelInfo info :  UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                     UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch ( UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JScrollPane Ta;
    private JTextField addressTf;
    private JButton editButton;
    private  JButton editSaveButton;
    private  JLabel jLabel1;
    private  JLabel jLabel2;
    private  JLabel jLabel3;
    private  JLabel jLabel4;
    private  JLabel jLabel5;
    private  JLabel jLabel6;
    private  JLabel jLabel7;
    private  JLabel jLabel8;
    private  JSpinner jSpinner1;
    private  JTextArea jTextArea1;
    private  JTextField mailTf;
    private  JTextField nameTf;
    private  JTextField phoneTf;
    private  JButton saveButton;
    private  JTextField searchTf;
    private  JButton search_byNameButton;
    private  JButton search_byPhoneButton;
    private  JButton showButton;
    // End of variables declaration
}
